version: "3.7"
services: 
    mongo:
        image: mongo:4.2.3
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    shift:
        build: ./services/shift
        ports: 
            - "8009:8080"
        links: 
            - mongo:mongo
        environment: 
            MONGO_SERVER_URL: mongodb://root:password@mongo